/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,html}"],
  theme: {
    screens: {
      lg: {
        raw: "screen and (max-width: 1200px)",
      },
      mq1050: {
        raw: "screen and (max-width: 1050px)",
      },
      mq750: {
        raw: "screen and (max-width: 750px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
    extend: {
      colors: {
        "border-100": "var(--color-border-100)",
        "border-200": "var(--color-border-200)",
        "border-300": "var(--color-border-300)",
        "border-400": "var(--color-border-400)",
        "border-50": "var(--color-border-50)",
        "border-500": "var(--color-border-500)",
        "border-600": "var(--color-border-600)",
        "border100-stroke": "var(--color-border100-stroke)",
        "neutral-100": "var(--color-neutral-100)",
        "neutral-200": "var(--color-neutral-200)",
        "neutral-300": "var(--color-neutral-300)",
        "neutral-400": "var(--color-neutral-400)",
        "neutral-50": "var(--color-neutral-50)",
        "neutral-500": "var(--color-neutral-500)",
        "neutral-600": "var(--color-neutral-600)",
        "neutral-700": "var(--color-neutral-700)",
        "neutral-800": "var(--color-neutral-800)",
        "neutral-900": "var(--color-neutral-900)",
        neutralsource: "var(--color-neutralsource)",
        "primary-100": "var(--color-primary-100)",
        "primary-200": "var(--color-primary-200)",
        "primary-300": "var(--color-primary-300)",
        "primary-400": "var(--color-primary-400)",
        "primary-50": "var(--color-primary-50)",
        "primary-500": "var(--color-primary-500)",
        "primary-600": "var(--color-primary-600)",
        "primary-700": "var(--color-primary-700)",
        "primary-800": "var(--color-primary-800)",
        "primary-900": "var(--color-primary-900)",
        primarysource: "var(--color-primarysource)",
        "secondary-50": "var(--color-secondary-50)",
        textdark: "var(--color-textdark)",
        textdisabled: "var(--color-textdisabled)",
        texterror: "var(--color-texterror)",
        texthint: "var(--color-texthint)",
        textlight: "var(--color-textlight)",
        textprimary: "var(--color-textprimary)",
        textsuccess: "var(--color-textsuccess)",
        textwarning: "var(--color-textwarning)",
      },
      fontFamily: {
        "body-lg": "var(--body-lg-font-family)",
        "body-md": "var(--body-md-font-family)",
        "body-sm": "var(--body-sm-font-family)",
        "heading-l": "var(--heading-l-font-family)",
        "heading-md": "var(--heading-md-font-family)",
        "heading-sm": "var(--heading-sm-font-family)",
        "heading-xl": "var(--heading-xl-font-family)",
        "heading-xs": "var(--heading-xs-font-family)",
        "heading-xxl": "var(--heading-xxl-font-family)",
        "label-lg": "var(--label-lg-font-family)",
        "label-md": "var(--label-md-font-family)",
        "label-sm": "var(--label-sm-font-family)",
        "title-lg": "var(--title-lg-font-family)",
        "title-md": "var(--title-md-font-family)",
        "title-sm": "var(--title-sm-font-family)",
      },
      boxShadow: {
        "focus-state-danger-active-shadow":
          "var(--focus-state-danger-active-shadow)",
        "focus-state-neutral-active-shadow":
          "var(--focus-state-neutral-active-shadow)",
        "focus-state-primary-active-shadow":
          "var(--focus-state-primary-active-shadow)",
        "focus-state-secondary-active-shadow":
          "var(--focus-state-secondary-active-shadow)",
        "focus-state-success-active-shadow":
          "var(--focus-state-success-active-shadow)",
        "focus-state-warning-active-shadow":
          "var(--focus-state-warning-active-shadow)",
        "shadow-lg": "var(--shadow-lg)",
        "shadow-md": "var(--shadow-md)",
        "shadow-s": "var(--shadow-s)",
        "shadow-xl": "var(--shadow-xl)",
        "shadow-xs": "var(--shadow-xs)",
        "shadow-xxl": "var(--shadow-xxl)",
      },
    },
  },
  plugins: [],
};
