/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  theme: {
    extend: {
      colors: {
        "border-100": "var(--border-100)",
        "border-200": "var(--border-200)",
        "border-300": "var(--border-300)",
        "border-400": "var(--border-400)",
        "border-50": "var(--border-50)",
        "border-500": "var(--border-500)",
        "border-600": "var(--border-600)",
        "border100-stroke": "var(--border100-stroke)",
        "neutral-100": "var(--neutral-100)",
        "neutral-200": "var(--neutral-200)",
        "neutral-300": "var(--neutral-300)",
        "neutral-400": "var(--neutral-400)",
        "neutral-50": "var(--neutral-50)",
        "neutral-500": "var(--neutral-500)",
        "neutral-600": "var(--neutral-600)",
        "neutral-700": "var(--neutral-700)",
        "neutral-800": "var(--neutral-800)",
        "neutral-900": "var(--neutral-900)",
        neutralsource: "var(--neutralsource)",
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-300": "var(--primary-300)",
        "primary-400": "var(--primary-400)",
        "primary-50": "var(--primary-50)",
        "primary-500": "var(--primary-500)",
        "primary-600": "var(--primary-600)",
        "primary-700": "var(--primary-700)",
        "primary-800": "var(--primary-800)",
        "primary-900": "var(--primary-900)",
        primarysource: "var(--primarysource)",
        "secondary-50": "var(--secondary-50)",
        textdark: "var(--textdark)",
        textdisabled: "var(--textdisabled)",
        texterror: "var(--texterror)",
        texthint: "var(--texthint)",
        textlight: "var(--textlight)",
        textprimary: "var(--textprimary)",
        textsuccess: "var(--textsuccess)",
        textwarning: "var(--textwarning)",
      },
      fontFamily: {
        "body-lg": "var(--body-lg-font-family)",
        "body-md": "var(--body-md-font-family)",
        "body-sm": "var(--body-sm-font-family)",
        "heading-l": "var(--heading-l-font-family)",
        "heading-md": "var(--heading-md-font-family)",
        "heading-sm": "var(--heading-sm-font-family)",
        "heading-xl": "var(--heading-xl-font-family)",
        "heading-xs": "var(--heading-xs-font-family)",
        "heading-xxl": "var(--heading-xxl-font-family)",
        "label-lg": "var(--label-lg-font-family)",
        "label-md": "var(--label-md-font-family)",
        "label-sm": "var(--label-sm-font-family)",
        "title-lg": "var(--title-lg-font-family)",
        "title-md": "var(--title-md-font-family)",
        "title-sm": "var(--title-sm-font-family)",
      },
      boxShadow: {
        "focus-state-danger-active-shadow":
          "var(--focus-state-danger-active-shadow)",
        "focus-state-neutral-active-shadow":
          "var(--focus-state-neutral-active-shadow)",
        "focus-state-primary-active-shadow":
          "var(--focus-state-primary-active-shadow)",
        "focus-state-secondary-active-shadow":
          "var(--focus-state-secondary-active-shadow)",
        "focus-state-success-active-shadow":
          "var(--focus-state-success-active-shadow)",
        "focus-state-warning-active-shadow":
          "var(--focus-state-warning-active-shadow)",
        "shadow-lg": "var(--shadow-lg)",
        "shadow-md": "var(--shadow-md)",
        "shadow-s": "var(--shadow-s)",
        "shadow-xl": "var(--shadow-xl)",
        "shadow-xs": "var(--shadow-xs)",
        "shadow-xxl": "var(--shadow-xxl)",
      },
    },
  },
  plugins: [],
};
